In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [113]:
data=pd.read_csv('C://Users//samsung//Desktop//air travel dataset.csv')

In [114]:
data.shape

(88532, 17)

In [115]:
data.head()

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Geometry Type,Properties Edtf Cessation,Properties Edtf Inception,Properties Flysfo Actual Timestamp,Properties Flysfo Airline,Properties Flysfo Base Airline,Properties Flysfo Base Flight Number,Date,Properties Flysfo Estimated Timestamp,Properties Flysfo Event,Properties Flysfo Flight Number,Properties Flysfo Gate,Route
0,-122.370943,37.61799,-118.353322,34.196704,MultiPoint,3/2/2020,uuuu,1583174520,AC,UA,5628.0,2-Mar-20,1583174520,D,AC4173,F5,SFO-BUR
1,-122.370943,37.61799,-118.353322,34.196704,MultiPoint,3/2/2020,uuuu,1583201580,AC,UA,5233.0,2-Mar-20,1583201580,D,AC4396,F15K,SFO-BUR
2,-122.370943,37.61799,-118.353322,34.196704,MultiPoint,3/2/2020,uuuu,1583195520,AC,UA,5318.0,2-Mar-20,1583195520,D,AC5514,F15K,SFO-BUR
3,-122.370943,37.61799,-118.353322,34.196704,MultiPoint,3/2/2020,uuuu,1583163840,AC,UA,5920.0,2-Mar-20,1583163840,D,AC4094,F15L,SFO-BUR
4,-122.370943,37.61799,-118.353322,34.196704,MultiPoint,3/2/2020,uuuu,1583187540,AC,UA,5717.0,2-Mar-20,1583187540,D,AC4388,F15L,SFO-BUR

In [116]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88532 entries, 0 to 88531
Data columns (total 17 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Geometry Coordinates 0 0               88532 non-null  float64
 1   Geometry Coordinates 0 1               88532 non-null  float64
 2   Geometry Coordinates 1 0               88532 non-null  float64
 3   Geometry Coordinates 1 1               88532 non-null  float64
 4   Geometry Type                          88532 non-null  object
 5   Properties Edtf Cessation              88532 non-null  object
 6   Properties Edtf Inception              88532 non-null  object
 7   Properties Flysfo Actual Timestamp     88532 non-null  int64
 8   Properties Flysfo Airline              88532 non-null  object
 9   Properties Flysfo Base Airline         54864 non-null  object
 10  Properties Flysfo Base Flight Number   54864 non-null  float64
 11  Date                                   88532 non-null  object
 12  Properties Flysfo Estimated Timestamp  88532 non-null  int64
 13  Properties Flysfo Event                88532 non-null  object
 14  Properties Flysfo Flight Number        88532 non-null  object
 15  Properties Flysfo Gate                 76139 non-null  object
 16  Route                                  88532 non-null  object
dtypes: float64(5), int64(2), object(10)
memory usage: 11.5+ MB

In [117]:
data.describe()

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Properties Flysfo Actual Timestamp,Properties Flysfo Base Flight Number,Properties Flysfo Estimated Timestamp
count,88532.000000,88532.000000,88532.000000,88532.000000,8.853200e+04,54864.000000,8.853200e+04
mean,-106.533160,37.006403,-106.956081,36.980280,1.584309e+09,2093.570356,1.584309e+09
std,42.653081,7.918635,41.988356,7.706460,7.488575e+05,1898.696397,7.484498e+05
min,-159.347789,-37.668253,-159.347789,-37.668253,1.583050e+09,1.000000,1.583050e+09
25%,-122.370943,36.081003,-122.370943,37.453966,1.583673e+09,624.000000,1.583673e+09
50%,-122.370943,37.617990,-122.370943,37.617990,1.584287e+09,1497.000000,1.584287e+09
75%,-111.980566,38.685533,-111.980566,37.617990,1.584918e+09,2691.000000,1.584919e+09
max,177.376360,64.822005,177.376360,64.822005,1.585723e+09,8844.000000,1.585731e+09

In [118]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Geometry Coordinates 0 0,88532.0,-1.065332e+02,42.653081,-1.593478e+02,-1.223709e+02,-1.223709e+02,-1.119806e+02,1.773764e+02
Geometry Coordinates 0 1,88532.0,3.700640e+01,7.918635,-3.766825e+01,3.608100e+01,3.761799e+01,3.868553e+01,6.482201e+01
Geometry Coordinates 1 0,88532.0,-1.069561e+02,41.988356,-1.593478e+02,-1.223709e+02,-1.223709e+02,-1.119806e+02,1.773764e+02
Geometry Coordinates 1 1,88532.0,3.698028e+01,7.706460,-3.766825e+01,3.745397e+01,3.761799e+01,3.761799e+01,6.482201e+01
Properties Flysfo Actual Timestamp,88532.0,1.584309e+09,748857.526766,1.583050e+09,1.583673e+09,1.584287e+09,1.584918e+09,1.585723e+09
Properties Flysfo Base Flight Number,54864.0,2.093570e+03,1898.696397,1.000000e+00,6.240000e+02,1.497000e+03,2.691000e+03,8.844000e+03
Properties Flysfo Estimated Timestamp,88532.0,1.584309e+09,748449.755323,1.583050e+09,1.583673e+09,1.584287e+09,1.584919e+09,1.585731e+09

In [119]:
data.corr()

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Properties Flysfo Actual Timestamp,Properties Flysfo Base Flight Number,Properties Flysfo Estimated Timestamp
Geometry Coordinates 0 0,1.000000,-0.348441,-0.136320,0.030727,0.017810,-0.206526,0.017752
Geometry Coordinates 0 1,-0.348441,1.000000,0.028355,-0.006391,-0.007848,0.068675,-0.007713
Geometry Coordinates 1 0,-0.136320,0.028355,1.000000,-0.352034,-0.006766,-0.230399,-0.005524
Geometry Coordinates 1 1,0.030727,-0.006391,-0.352034,1.000000,-0.008942,0.035973,-0.009823
Properties Flysfo Actual Timestamp,0.017810,-0.007848,-0.006766,-0.008942,1.000000,0.025551,0.999925
Properties Flysfo Base Flight Number,-0.206526,0.068675,-0.230399,0.035973,0.025551,1.000000,0.025051
Properties Flysfo Estimated Timestamp,0.017752,-0.007713,-0.005524,-0.009823,0.999925,0.025051,1.000000

In [120]:
data.isnull().any()

Geometry Coordinates 0 0                 False
Geometry Coordinates 0 1                 False
Geometry Coordinates 1 0                 False
Geometry Coordinates 1 1                 False
Geometry Type                            False
Properties Edtf Cessation                False
Properties Edtf Inception                False
Properties Flysfo Actual Timestamp       False
Properties Flysfo Airline                False
Properties Flysfo Base Airline            True
Properties Flysfo Base Flight Number      True
Date                                     False
Properties Flysfo Estimated Timestamp    False
Properties Flysfo Event                  False
Properties Flysfo Flight Number          False
Properties Flysfo Gate                    True
Route                                    False
dtype: bool

In [121]:
data.columns

Index(['Geometry Coordinates 0 0', 'Geometry Coordinates 0 1',
       'Geometry Coordinates 1 0', 'Geometry Coordinates 1 1', 'Geometry Type',
       'Properties Edtf Cessation', 'Properties Edtf Inception',
       'Properties Flysfo Actual Timestamp', 'Properties Flysfo Airline',
       'Properties Flysfo Base Airline',
       'Properties Flysfo Base Flight Number', 'Date',
       'Properties Flysfo Estimated Timestamp', 'Properties Flysfo Event',
       'Properties Flysfo Flight Number', 'Properties Flysfo Gate', 'Route'],
      dtype='object')

In [122]:
data['Properties Flysfo Base Flight Number'].unique()

array([5628., 5233., 5318., ..., 3755., 1194.,  558.])

In [123]:
data['Properties Flysfo Base Flight Number']=data['Properties Flysfo Base Flight Number'].fillna(data['Properties Flysfo Base Flight Number'].median())

In [124]:
data['Properties Flysfo Base Flight Number'].isnull().sum()

0

In [125]:
new_data=data.drop(['Geometry Type','Properties Edtf Inception','Properties Flysfo Airline','Properties Flysfo Base Airline','Date',
                          'Properties Flysfo Event', 'Properties Flysfo Flight Number', 'Properties Flysfo Gate', 'Route'],axis=1)
new_data

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Properties Edtf Cessation,Properties Flysfo Actual Timestamp,Properties Flysfo Base Flight Number,Properties Flysfo Estimated Timestamp
0,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583174520,5628.0,1583174520
1,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583201580,5233.0,1583201580
2,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583195520,5318.0,1583195520
3,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583163840,5920.0,1583163840
4,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583187540,5717.0,1583187540
...,...,...,...,...,...,...,...,...
88527,-122.370943,37.61799,-117.587749,34.059934,3/2/2020,1583166420,5249.0,1583166420
88528,-122.370943,37.61799,-117.587749,34.059934,3/2/2020,1583217120,5611.0,1583217120
88529,-122.370943,37.61799,-117.587749,34.059934,3/2/2020,1583170980,5371.0,1583170980
88530,-122.370943,37.61799,-117.587749,34.059934,3/2/2020,1583197320,5425.0,1583197320
88531,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583209020,1496.0,1583209020

In [126]:
new_data['estimated_time']=pd.to_datetime(new_data['Properties Flysfo Estimated Timestamp'],unit='s')
new_data

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Properties Edtf Cessation,Properties Flysfo Actual Timestamp,Properties Flysfo Base Flight Number,Properties Flysfo Estimated Timestamp,estimated_time
0,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583174520,5628.0,1583174520,2020-03-02 18:42:00
1,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583201580,5233.0,1583201580,2020-03-03 02:13:00
2,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583195520,5318.0,1583195520,2020-03-03 00:32:00
3,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583163840,5920.0,1583163840,2020-03-02 15:44:00
4,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583187540,5717.0,1583187540,2020-03-02 22:19:00
...,...,...,...,...,...,...,...,...,...
88527,-122.370943,37.61799,-117.587749,34.059934,3/2/2020,1583166420,5249.0,1583166420,2020-03-02 16:27:00
88528,-122.370943,37.61799,-117.587749,34.059934,3/2/2020,1583217120,5611.0,1583217120,2020-03-03 06:32:00
88529,-122.370943,37.61799,-117.587749,34.059934,3/2/2020,1583170980,5371.0,1583170980,2020-03-02 17:43:00
88530,-122.370943,37.61799,-117.587749,34.059934,3/2/2020,1583197320,5425.0,1583197320,2020-03-03 01:02:00
88531,-122.370943,37.61799,-118.353322,34.196704,3/2/2020,1583209020,1496.0,1583209020,2020-03-03 04:17:00

In [127]:
new_data=new_data.drop(['Properties Edtf Cessation','Properties Flysfo Estimated Timestamp'],axis=1)
new_data

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Properties Flysfo Actual Timestamp,Properties Flysfo Base Flight Number,estimated_time
0,-122.370943,37.61799,-118.353322,34.196704,1583174520,5628.0,2020-03-02 18:42:00
1,-122.370943,37.61799,-118.353322,34.196704,1583201580,5233.0,2020-03-03 02:13:00
2,-122.370943,37.61799,-118.353322,34.196704,1583195520,5318.0,2020-03-03 00:32:00
3,-122.370943,37.61799,-118.353322,34.196704,1583163840,5920.0,2020-03-02 15:44:00
4,-122.370943,37.61799,-118.353322,34.196704,1583187540,5717.0,2020-03-02 22:19:00
...,...,...,...,...,...,...,...
88527,-122.370943,37.61799,-117.587749,34.059934,1583166420,5249.0,2020-03-02 16:27:00
88528,-122.370943,37.61799,-117.587749,34.059934,1583217120,5611.0,2020-03-03 06:32:00
88529,-122.370943,37.61799,-117.587749,34.059934,1583170980,5371.0,2020-03-02 17:43:00
88530,-122.370943,37.61799,-117.587749,34.059934,1583197320,5425.0,2020-03-03 01:02:00
88531,-122.370943,37.61799,-118.353322,34.196704,1583209020,1496.0,2020-03-03 04:17:00

In [128]:
new_data['actual_time']=pd.to_datetime(new_data['Properties Flysfo Actual Timestamp'],unit='s')
new_data

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Properties Flysfo Actual Timestamp,Properties Flysfo Base Flight Number,estimated_time,actual_time
0,-122.370943,37.61799,-118.353322,34.196704,1583174520,5628.0,2020-03-02 18:42:00,2020-03-02 18:42:00
1,-122.370943,37.61799,-118.353322,34.196704,1583201580,5233.0,2020-03-03 02:13:00,2020-03-03 02:13:00
2,-122.370943,37.61799,-118.353322,34.196704,1583195520,5318.0,2020-03-03 00:32:00,2020-03-03 00:32:00
3,-122.370943,37.61799,-118.353322,34.196704,1583163840,5920.0,2020-03-02 15:44:00,2020-03-02 15:44:00
4,-122.370943,37.61799,-118.353322,34.196704,1583187540,5717.0,2020-03-02 22:19:00,2020-03-02 22:19:00
...,...,...,...,...,...,...,...,...
88527,-122.370943,37.61799,-117.587749,34.059934,1583166420,5249.0,2020-03-02 16:27:00,2020-03-02 16:27:00
88528,-122.370943,37.61799,-117.587749,34.059934,1583217120,5611.0,2020-03-03 06:32:00,2020-03-03 06:32:00
88529,-122.370943,37.61799,-117.587749,34.059934,1583170980,5371.0,2020-03-02 17:43:00,2020-03-02 17:43:00
88530,-122.370943,37.61799,-117.587749,34.059934,1583197320,5425.0,2020-03-03 01:02:00,2020-03-03 01:02:00
88531,-122.370943,37.61799,-118.353322,34.196704,1583209020,1496.0,2020-03-03 04:17:00,2020-03-03 04:17:00

In [129]:
new_data=new_data.drop(['Properties Flysfo Actual Timestamp'],axis=1)
new_data

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Properties Flysfo Base Flight Number,estimated_time,actual_time
0,-122.370943,37.61799,-118.353322,34.196704,5628.0,2020-03-02 18:42:00,2020-03-02 18:42:00
1,-122.370943,37.61799,-118.353322,34.196704,5233.0,2020-03-03 02:13:00,2020-03-03 02:13:00
2,-122.370943,37.61799,-118.353322,34.196704,5318.0,2020-03-03 00:32:00,2020-03-03 00:32:00
3,-122.370943,37.61799,-118.353322,34.196704,5920.0,2020-03-02 15:44:00,2020-03-02 15:44:00
4,-122.370943,37.61799,-118.353322,34.196704,5717.0,2020-03-02 22:19:00,2020-03-02 22:19:00
...,...,...,...,...,...,...,...
88527,-122.370943,37.61799,-117.587749,34.059934,5249.0,2020-03-02 16:27:00,2020-03-02 16:27:00
88528,-122.370943,37.61799,-117.587749,34.059934,5611.0,2020-03-03 06:32:00,2020-03-03 06:32:00
88529,-122.370943,37.61799,-117.587749,34.059934,5371.0,2020-03-02 17:43:00,2020-03-02 17:43:00
88530,-122.370943,37.61799,-117.587749,34.059934,5425.0,2020-03-03 01:02:00,2020-03-03 01:02:00
88531,-122.370943,37.61799,-118.353322,34.196704,1496.0,2020-03-03 04:17:00,2020-03-03 04:17:00

In [130]:
X=new_data.drop(['estimated_time','actual_time'],axis=1)
y=new_data['estimated_time']

In [137]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.4,random_state=80)

In [138]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [144]:
test_data=new_data.drop(['estimated_time','actual_time'],axis=1)

test_data

,Geometry Coordinates 0 0,Geometry Coordinates 0 1,Geometry Coordinates 1 0,Geometry Coordinates 1 1,Properties Flysfo Base Flight Number
0,-122.370943,37.61799,-118.353322,34.196704,5628.0
1,-122.370943,37.61799,-118.353322,34.196704,5233.0
2,-122.370943,37.61799,-118.353322,34.196704,5318.0
3,-122.370943,37.61799,-118.353322,34.196704,5920.0
4,-122.370943,37.61799,-118.353322,34.196704,5717.0
...,...,...,...,...,...
88527,-122.370943,37.61799,-117.587749,34.059934,5249.0
88528,-122.370943,37.61799,-117.587749,34.059934,5611.0
88529,-122.370943,37.61799,-117.587749,34.059934,5371.0
88530,-122.370943,37.61799,-117.587749,34.059934,5425.0
88531,-122.370943,37.61799,-118.353322,34.196704,1496.0

In [146]:
predictions=model.predict(test_data)

In [147]:
y['estimated_time']=predictions

C:\Users\samsung\AppData\Local\Temp/ipykernel_5228/561313885.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['estimated_time']=predictions

In [148]:
y

0                                               2020-03-02 18:42:00
1                                               2020-03-03 02:13:00
2                                               2020-03-03 00:32:00
3                                               2020-03-02 15:44:00
4                                               2020-03-02 22:19:00
                                        ...
88528                                           2020-03-03 06:32:00
88529                                           2020-03-02 17:43:00
88530                                           2020-03-03 01:02:00
88531                                           2020-03-03 04:17:00
estimated_time    [1.584316005518049e+18, 1.584315147040131e+18,...
Name: estimated_time, Length: 88533, dtype: object

In [150]:
accuracy=model.score(x,predictions)
print(accuracy*100,'%')

100.0 %